/* Generated by scripts/optimize-images.mjs — do not edit by hand. */

export const IMAGE_VARIANTS: Record<string, number[]> = {
  '/img/avatar.webp': [64, 128, 168, 210, 256],
  '/img/fan-1.webp': [64, 128, 168, 210, 256, 338, 420, 640, 750, 840],
  '/img/fan-2.webp': [64, 128, 168, 210, 256, 338, 420, 640, 750, 840],
  '/img/fan-4.webp': [64, 128, 168, 210, 256, 338, 420, 640, 750, 840],
  '/img/fan-5.webp': [64, 128, 168, 210, 256, 338, 420, 640, 750, 840],
  '/img/fan-6.webp': [64, 128, 168, 210, 256, 338, 420, 640, 750, 840],
  '/img/me-cutout.webp': [64, 128, 168, 210, 256, 338, 420, 640, 750, 800],
};
